apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-html
data:
  index.html: |
    <html>
      <head><title>Web Belajar K8s</title></head>
      <body>
        <h1>Halo dari ConfigMap!</h1>
        <p>Halaman ini disuntikkan langsung ke dalam Pod Nginx tanpa build ulang image.</p>
      </body>
    </html>